export const DEFAULT_KEYS = {
    menu_session: "1",
    menu_encounter: "2",
    menu_characters: "3",
    menu_states: "4",
    menu_history: "5",
    global_search: "Ctrl+K",
    characters: {
        search_focus: "Ctrl+Shift+F",
        next: "arrowdown",
        prev: "arrowup",
        delete: "delete",
        rename: "f2",
        description: "Z",
        states: "X",
        history: "C",
    },
    states: {
        search_focus: "Ctrl+Shift+F",
        next: "arrowdown",
        prev: "arrowup",
        delete: "delete",
        rename: "f2",
        description: "Z",
        triggers: "X",
    },
};
